### ISSUE TITLE
Can it work with minio?

### ISSUE THREAD

**Issue by mailanetworks** [andersundsehr/aus_driver_amazon_s3#62]
How about making it work with Minio Storage https://github.com/minio/ ?

Thanks,

**Comment by Lagerregal** [comment]
To be honest I don't see a use case for this. But I'm open for pull requests and forks!

**Comment by poliander** [comment]
@mailanetworks

It does not work so far, as I can see there are some AWS URLs hardcoded.

@Lagerregal 

We're running TYPO3 in a Kubernetes cluster and are using MinIO as a self-hosted AWS S3 replacement. This can be accessed from other client applications, too, since it aims to be ~100% compatible to AWS S3. Using the currently assigned physical storage with TYPO3 would be a treat.

**Comment by christophlehmann** [comment]
>We're running TYPO3 in a Kubernetes cluster and are using MinIO as a self-hosted AWS S3 replacement. This can be accessed from other client applications, too, since it aims to be ~100% compatible to AWS S3. Sharing the physical storage currently assigned to MinIO with TYPO3 would be a treat.

Same here. 

Nice to see a working solution some years later 👍
