### ISSUE TITLE
PHP 7.2 Deprecations

### ISSUE THREAD

**Issue by tomasnorre** [andersundsehr/aus_driver_amazon_s3#65]
Hi,

There are few deprecated lines in the extension, would be great if this would be updated.
![Screenshot 2019-10-24 at 07 51 15](https://user-images.githubusercontent.com/1212481/67457181-3d140d00-f633-11e9-989f-f0f4b869cb84.png)

I would be happy to provide a PR, when I get to this in my backlog, but isn't a big thing. It's just a warning, no fatal.

**Comment by tomasnorre** [comment]
Just notices which files that has this warning.

Why don't you require Guzzle over composer? instead of committing it to your repository?

**Comment by Lagerregal** [comment]
Hi @tomasnorre, thanks for your hint! This warning is triggered because of the AWS SDK which is included for legacy reasons. It's only loaded if you install the extension without Composer. Using this extension with Composer (highly recommended!) you should use the latest version of AWS SDK and Guzzle.

**Comment by tomasnorre** [comment]
Hmm. It was installed via composer, the project haven been composer based for more than 3 years, so not sure if that's the case. 

It's in a TYPO3 8 ELTS version, so perhaps the Guzzle included there gives the wrong AWS Version due to sub-dependencies.
